### ISSUE TITLE
Not able to find devices

### ISSUE THREAD

**Issue by pjmpessers** [gruijter/com.gruijter.netgear#47] opened 2020-07-21 18:50 UTC
It find my router, but it can't find devices. I use fw v 5.0.0 rc 17. It removed sdk 1 and is only compatible te sdk 2 and 3.

========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.2.0
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:5.0.0-rc.17 app: 3.2.1
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.3.92_1.0.43,RegionTag:RAX80_WW,Region:ww,Model:RAX80,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.23,ReadyShareSupportedLevel:25,XCloudSupported:1,LoginMethod:2.0,DeviceMode:0,isBlankState:0,host:192.168.1.1,port:5000}]
t = 129.761
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 130.462
trying to getInfo...
{ModelName:RAX80,Description:Netgear Smart Wizard 3.0, specification 0.7 version,SerialNumber:**********,Firmwareversion:V1.0.3.92,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.43,Hardwareversion:RAX80,Otherhardwareversion:N/A,FirstUseDate:Tuesday, 31 Dec 2019 00:13:45,DeviceName:RAX80,FirmwareDLmethod:Null,FirmwareLastUpdate:Null,FirmwareLastChecked:Null,DeviceMode:0,DeviceModeCapability:0,DeviceNameUserSet:RAX80}
t = 130.823
trying to getSystemInfo...
{NewCPUUtilization:0,NewPhysicalMemory:256,NewMemoryUtilization:58,NewPhysicalFlash:128,NewAvailableFlash:128}
t = 131.131
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,CircleParentalControl:2.0,MaxMonthlyTrafficLimitation:4095000000,AccessControl:1.0,SpeedTest:2.0,BitDefenderSecurity:1.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0,PasswordReset:2.0,SupportXMLEncoded:1.0,SupportAXMode:1.0,SupportWPA3:1.0,DeviceTypeIcon:2.1,ControlledFwRollout:1.0}
t = 131.51
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:3C3786B9EAF2,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 131.808
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:84.31.240.6,NewSubnetMask:255.255.254.0,NewAddressingType:DHCP,NewDefaultGateway:84.31.240.1,NewMACAddress:3C3786B9EAF3,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:84.116.46.22 84.116.46.23 }
t = 132.133
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 132.51
trying to get trafficMeter...
{newTodayUpload:4821,newTodayDownload:3958,newMonthUpload:120026,newMonthDownload:94586}
t = 132.814
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 133.139
trying to get System Uptime (hh:mm:ss)...
06:17:43
t = 133.478
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:1,NewDaylightSaving:1}
t = 133.809
trying to get Parental Control Status...
Parental Control Enabled: false
t = 134.872
trying to get Qos Status...
Qos Enabled: false
t = 135.177
trying to get Qos Bandwidth options...
{newUplinkBandwidth:25.45,newDownlinkBandwidth:240.49,enabled:2}
t = 135.504
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
selected channel 5.0G-1: 48
Available channels 5.0G-2: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-2 channel is not available
t = 137.527
trying to get Smart Connect Status...
Smart Connect Enabled: true
t = 138.944
trying to get router logs...
last log: [DHCP IP: (192.168.1.5)] to MAC address D8:0D:17:14:7B:43, Tuesday, Jul 21,2020 20:46:58
t = 139.192
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi enabled: false, method: 2
5.0G-2 Guest wifi enabled: false
t = 139.983
trying to get Device Access Control Status...
Block Device Enabled: true
t = 140.323
trying to get attachedDevices method 1...
Number of attached devices: 28
First attached device:
{IP:192.168.1.5,Name:HS100,MAC:D8:0D:17:14:7B:43,ConnectionType:wireless,Linkspeed:72,SignalStrength:80,AllowOrBlock:Allow}
t = 142.533
trying to get attachedDevices method 2...
Number of attached devices: 36
First attached device:
{IP:192.168.1.40,Name:Chromecast-Ultra,NameUserSet:true,MAC:44:09:B8:31:7C:17,ConnectionType:wired,SignalStrength:100,AllowOrBlock:Allow,Schedule:false,DeviceType:30,DeviceTypeUserSet:false,DeviceTypeV2:6,DeviceTypeNameV2:Media Streamer,Upload:0,Download:0,QosPriority:4,DeviceModelUserSet:false,DeviceModel:Chromecast,Grouping:0,SchedulePeriod:0,ConnAPMAC:3C:37:86:B9:EA:F2}
t = 147.721
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:1.0.3.92,newVersion:,releaseNote:}
t = 153.658
trying to logout...
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:...,queue:{queue:{},overheat:1595337115861,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 153.703
test finished without errors :)

**Comment by gruijter** [comment] 2020-07-21 21:16
Well, the test runs perfect. In homey you have to add the router itself as a device first. Did you do that?

**Comment by gruijter** [comment] 2020-07-21 21:19
However... there is a weird discrepancy between getAttachedDevices method 1 and 2 (28 vs 36 detected devices). In the Homey router settings try attached method old or new, and see what happens then.

**Comment by pjmpessers** [comment] 2020-07-21 22:24
I get the router without a problem. It is when it search for devices it gets a time out. In the logging it sees the devices. But it can't be found in the homey devices setup.

2020-07-22 00:27:06 [err] [MyApp] unhandledRejection! TypeError: Cannot read property 'id' of undefined at EventEmitter. (/drivers/attached_device/driver.js:133:31) at EventEmitter.emit (events.js:311:20) at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:3396 at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by pjmpessers** [comment] 2020-07-21 22:26
What do you mean setup old or new? Remove all devices and router and set it up again? I did that.

**Comment by gruijter** [comment] 2020-07-22 01:45
![Screenshot_20200722-034256_Homey](https://user-images.githubusercontent.com/19174120/88124522-9f536b80-cbcd-11ea-9162-2734d822678b.jpg)

Attachef devices method from auto > old  > new

**Comment by pjmpessers** [comment] 2020-07-22 03:31
Found it. But new or old. It can't be found.

2020-07-22 05:28:30 [err] [MyApp] unhandledRejection! TypeError: Cannot read property 'id' of undefined at EventEmitter. (/drivers/attached_device/driver.js:133:31) at EventEmitter.emit (events.js:311:20) at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:3396 at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-22 05:28:29 pairing started by user
2020-07-22 05:27:10 [netgear] [0] device ready: RAX80 id: 5HS4977HA02F3
2020-07-22 05:27:05 [netgear] [0] Access control enable requested
2020-07-22 05:26:56 [netgear] [0] Traffic meter enable requested
2020-07-22 05:26:56 [netgear] [0] retrieving knownDevices from persistent storage
2020-07-22 05:26:56 [netgear] [0] device init: RAX80 id: 5HS4977HA02F3
2020-07-22 05:26:46 [netgear] [0] router device settings changed
2020-07-22 05:25:55 [err] [MyApp] unhandledRejection! TypeError: Cannot read property 'id' of undefined at EventEmitter. (/drivers/attached_device/driver.js:133:31) at EventEmitter.emit (events.js:311:20) at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:3396 at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-22 05:25:54 pairing started by user
2020-07-22 05:25:21 [log] [MyApp] logfile deleted

**Comment by gruijter** [comment] 2020-07-22 03:47
Is this a recent issue (did it work before?) Or did it never work for you?

Looks like a timing issue. Homey tries to get the attached device while the router isnt fully initialized. Weird.

**Comment by pjmpessers** [comment] 2020-07-22 05:40
It did work. But after the update of homey to fw 5.0.0 rc17 i saw that the router was okay and the app didn't crash, but red exclamations marks by the devices and after removing i couldn't set it up again.


-------- Oorspronkelijk bericht --------
Van: gruijter <notifications@github.com>
Datum: 22-07-2020 05:48 (GMT+01:00)
Aan: "gruijter/com.gruijter.netgear" <com.gruijter.netgear@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [gruijter/com.gruijter.netgear] Not able to find devices (#47)


Is this a recent issue (did it work before?) Or did it never work for you?

**Comment by pjmpessers** [comment] 2020-07-24 20:35
Same problem exist on fw5.0.0 rc18

**Comment by gruijter** [comment] 2020-07-24 20:53
Can you pair a new attached device? Or did you keep all the attached devices when you deleted/paired the router device?

**Comment by pjmpessers** [comment] 2020-07-24 21:05
First i deleted just only the devices, because it gave the red exclamation mark and tried to attach it again but failed. Then i removed also the router. The router was easy to setup. The devices not.

**Comment by pjmpessers** [comment] 2020-07-24 21:06
![Screenshot_20200724-230617_Homey](https://user-images.githubusercontent.com/34476404/88435370-546e6980-ce02-11ea-9f12-2b2e21ef80a3.jpg)

**Comment by pjmpessers** [comment] 2020-07-27 16:06
Did a firmware rollback to fw4.2.0 and noticed i could add devices without a problem again. Because of strange zigbee problems i did go back to FW 5.0.0 rc18. On that moment i saw that i added the wrong mobile phone so tried to add the right phone, but on fw 5.0.0 rc18 it is impossible and i get a time out after 30000ms. The devices that are attached with fw 4.2.0 keeps working. So trying to attach a new device is not possible with the new firmware.

Just wanted to let you know.

**Comment by gruijter** [comment] 2020-07-27 17:01
Ah, that is interesting. Thx 4 letting me know. Will investigate (on v5 myself without issues)

**Comment by pjmpessers** [comment] 2020-07-27 18:03
Thanks.

**Comment by gruijter** [comment] 2020-08-11 07:52
I can reproduce the problem. In Homey V5 something changed in the frontend (the part that runs on your mobile device). I have to figure out what has changed, and how to fix it without breaking compatibility for Homey V2/3/4.

Hang tight :)

**Comment by pjmpessers** [comment] 2020-08-11 10:04
Thank you. Nice to hear that you found the problem and are taking action.
I will wait. 👍

**Comment by gruijter** [comment] 2020-08-11 12:06
fixed in 3.2.2

https://homey.app/a/com.gruijter.netgear/test/

**Closed as completed by gruijter** 2020-08-11 12:06 UTC
