### ISSUE TITLE
R8000 Error: Failed to login when try to add router device

### ISSUE THREAD

**Issue by mwolfs** [gruijter/com.gruijter.netgear#41] opened 2020-02-05 21:12 UTC
Hi,

I bought a new R8000 and initially I got your app working on Homey. It's a great app but after 1 day  app gave an error. After router reboot it was ok again but after a day again app hang. Also nighthawk app was hanging I then removed the app from Homey to check if Nighthawk app was also hanging after a day. But without Homey app running this seems stable. I then saw issue #39 and a new version of the app which I hoped would solve my problem. But now I'm not able to install the app anymore if gives an error: Failed to login. (Tried password several times also after router reboot) Please find below the output from the test. Hope you are able to fix the problem 

========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.9
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:3.2.1 app: 3.0.5
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.4.46_10.1.63,RegionTag:R8000_WW,Region:ww,Model:R8000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:1,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,SmartNetworkSupported:0,DeviceMode:0,host:192.168.1.1,port:5000}]
t = 3.55
trying to login with method 1...
method 1 ok.
trying to login with method 2...
method 2 ok.
trying to login with auto method...
reported login method: 2
t = 3.805
trying to getInfo...
{ModelName:R8000,Description:Netgear Smart Wizard 3.0, specification 0.7 version,SerialNumber:**********,Firmwareversion:V1.0.4.46,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010),VPNVersion:N/A,OthersoftwareVersion:10.1.63,Hardwareversion:R8000,Otherhardwareversion:N/A,FirstUseDate:Wednesday, 29 Jan 2020 16:38:42,DeviceName:R8000,FirmwareDLmethod:Null,FirmwareLastUpdate:Null,FirmwareLastChecked:Null,DeviceMode:0}
t = 3.942
trying to get System Uptime (hh:mm:ss)...
00:53:16
t = 3.981
trying to getSystemInfo...
{NewCPUUtilization:35,NewPhysicalMemory:256,NewMemoryUtilization:55,NewPhysicalFlash:128,NewAvailableFlash:128}
t = 4.039
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,CircleParentalControl:2.0,MaxMonthlyTrafficLimitation:4095000000,AccessControl:1.0,SpeedTest:2.0,BitDefenderSecurity:1.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0}
t = 4.083
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+1,NewDaylightSaving:0}
t = 4.131
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:3C3786C6B4FF,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 4.174
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:89.nnn.nnn.nnn,NewSubnetMask:255.255.254.0,NewAddressingType:DHCP,NewDefaultGateway:89.nnn.nnn.n,NewMACAddress:3C3786C6B4FF,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:84.116.46.22 84.nnn.nn.nn }
t = 4.219
trying to get Parental Control Status...
Parental Control Enabled: false
t = 4.38
trying to get Qos Status...
Qos Enabled: true
t = 4.421
trying to get Qos Bandwidth options...
{newUplinkBandwidth:25.66,newDownlinkBandwidth:214.15,enabled:2}
t = 4.471
trying to get Device Access Control Status...
Block Device Enabled: true
t = 4.514
trying to get attachedDevices method 1...
Number of attached devices: 14
First attached device: {\IP\:\192.168.1.2\,\Name\:\bosch camera\,\MAC\:\68:A4:0E:18:C9:5D\,\ConnectionType\:\wireless\,\Linkspeed\:39,\SignalStrength\:51,\AllowOrBlock\:\Allow\}
t = 9.709
trying to get attachedDevices method 2...
Number of attached devices: 15
First attached device: {\IP\:\192.168.1.2\,\Name\:\bosch camera\,\NameUserSet\:true,\MAC\:\68:A4:0E:18:C9:5D\,\ConnectionType\:\2.4GHz\,\SSID\:\Ziggo6245\,\Linkspeed\:39,\SignalStrength\:51,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceType\:2,\DeviceTypeUserSet\:true,\Upload\:0,\Download\:0,\QosPriority\:3,\DeviceModel\:\--\,\Grouping\:0,\SchedulePeriod\:0}
t = 14.073
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
selected channel 5.0G-1: 100
Available channels 5.0G-2: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-2 channel is not available
t = 14.331
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 14.511
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi enabled: false, method: 2
5.0G-2 Guest wifi enabled: false
t = 14.645
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 14.684
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 14.725
trying to get trafficMeter...
{newTodayUpload:208.49,newTodayDownload:1823,newMonthUpload:208.49,newMonthDownload:1823}
t = 14.779
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:1.0.4.46,newVersion:,releaseNote:}
t = 20.182
trying to get router logs...
last log: [DHCP IP: (192.168.1.11)] to MAC address 94:A1:A2:84:CA:CA, Wednesday, Feb 05,2020 21:53:34
t = 20.232
trying to logout...
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:...}
t = 22.285
test finished without errors :)

**Comment by gruijter** [comment] 2020-02-06 10:39
probably you have the same as here: https://github.com/gruijter/com.gruijter.netgear/issues/40#issuecomment-582805515

follow the setup instructions, and alway PTP (power off and on) your router before and after doing so!

**Comment by mwolfs** [comment] 2020-02-06 16:41
No luck :-( did the following:
Uninstall the app on Homey
PTP of Homey
PTP of the router
Installed app v3.07
Checked if I was on same network as Homey 2,4GHz
Logon in Nighthawk app with admin user to test password
Then installed new device with ip 192.168.1.1 and soap port 5000 and password but the immediately after a second got error Error: Failed to login 
Check the log and see the following:


2020-02-06 17:34:59 [err] [ManagerDrivers] [netgear] Pair error: Failed to login 
2020-02-06 17:34:58 [netgear] Checking router settings from frontend 
2020-02-06 17:34:53 [netgear] { Firmware: 'V1.0.4.46_10.1.63', RegionTag: 'R8000_WW', Region: 'ww', Model: 'R8000', InternetConnectionStatus: 'Up', ParentalControlSupported: '1', CircleEnabled: '1', OpenDNSEnabled: '0', SOAPVersion: '3.21', LoginMethod: '2.0', ReadyShareSupportedLevel: '29', XCloudSupported: '1', SmartNetworkSupported: '0', DeviceMode: '0', host: '192.168.1.1', port: 5000 } 
2020-02-06 17:34:53 [netgear] discovery started from frontend

If I than run Test with same Ip port and password it finishes without errors..

**Comment by gruijter** [comment] 2020-02-06 17:45
I think I can reproduce the problem now. Will look into it further.

**Comment by mwolfs** [comment] 2020-02-06 17:54
Thanks a lot!

**Comment by gruijter** [comment] 2020-02-06 18:54
Fixed in v3.0.8!

https://homey.app/a/com.gruijter.netgear/test/

Thanks for reporting!

**Comment by mwolfs** [comment] 2020-02-06 19:12
Yes works again!!!!  Thanks for the good service will check if problem with hanging router is also solved now.

**Comment by Hmvink** [comment] 2020-02-06 20:41
The login problem is solved but the connected/disconnected status is not updated.

**Comment by gruijter** [comment] 2020-02-06 20:54
Can you post a screenshot of the router advanced settings in Homey?

**Comment by Hmvink** [comment] 2020-02-07 05:51
![2020-2-7_6-48-59](https://user-images.githubusercontent.com/47409888/74004491-2f7e5b00-4976-11ea-94dc-efa5f6c4f600.PNG)

**Comment by gruijter** [comment] 2020-02-07 06:13
Put the 3 reporting options to 'no', set the connected device method to 'old', and set the offline after to '600' (if you want faster detection for individual devices, add them as attached device in Homey, and fine-tune the offline after there).

Then ptp the router. Let me know if that keeps it stable.

**Comment by Hmvink** [comment] 2020-02-07 10:13
Hi Robin, I did all of the above but a device coming online or going offline is still not detected. The number of online device is reported correctly so there is communication with the router. If you need more info please let me know.

**Comment by gruijter** [comment] 2020-02-07 10:54
If you say the number of connected devices is correct, the app must detect also that a device goes online or offline. How do you notice that a device is not correctly reported? Can you post the app logs here? They should reflect all devices going online and offline.

**Comment by Hmvink** [comment] 2020-02-07 11:30
2020-02-07 11:15:59 [netgear] [0] Offline: 4C:24:98:48:99:3D RING
2020-02-07 11:06:59 [netgear] [0] Online: 30:9C:23:90:B4:5B MSI-GS65 192.168.210.110
2020-02-07 11:06:59 [netgear] [0] new device added: 30:9C:23:90:B4:5B MSI-GS65
2020-02-07 11:06:59 [netgear] [0] deleting corrupt device undefined
2020-02-07 11:06:59 [netgear] [0] Online: A0:04:60:1B:6A:FC Unknown 192.168.210.114
2020-02-07 09:53:54 [netgear] [0] Offline: 28:80:88:DC:D3:F4 Orbi Schuur
2020-02-07 09:53:54 [netgear] [0] Offline: 28:80:88:DC:B7:5C Orbi Zolder
2020-02-07 09:48:53 [netgear] [0] Offline: A0:04:60:1B:6A:FC Unknown
2020-02-07 09:44:53 [netgear] [0] Online: 4C:24:98:48:99:3D RING 192.168.210.106
2020-02-07 09:44:33 [log] [MyApp] test ready
2020-02-07 09:44:03 [log] [MyApp] Router compatibility test started
2020-02-07 09:42:58 [log] [MyApp] Router discovery started
2020-02-07 09:42:53 [netgear] [0] Online: 28:80:88:DC:D3:F4 Orbi Schuur 192.168.210.109
2020-02-07 09:42:53 [netgear] [0] new device added: 28:80:88:DC:D3:F4 Orbi Schuur
2020-02-07 09:42:53 [netgear] [0] deleting corrupt device undefined
2020-02-07 09:42:53 [netgear] [0] Online: 28:80:88:DC:B7:5C Orbi Zolder 192.168.210.102
2020-02-07 09:42:53 [netgear] [0] new device added: 28:80:88:DC:B7:5C Orbi Zolder
2020-02-07 09:42:53 [netgear] [0] deleting corrupt device undefined
2020-02-07 09:40:51 [err] [ManagerDrivers] [netgear] [0] DevicePoll Failed to login
2020-02-07 09:40:08 [err] [ManagerDrivers] [netgear] [0] DevicePoll Failed to login
2020-02-07 09:37:39 [netgear] [0] Access control enable requested
2020-02-07 09:37:39 [netgear] [0] retrieving knownDevices from persistent storage
2020-02-07 09:37:39 [netgear] [0] device init: Netgear Orbi router id: 5M328C5P0F30D
2020-02-07 09:37:39 [netgear] NetgearDriver onInit
2020-02-07 09:37:38 [log_analyzer] LogAnalyzerDriver onInit
2020-02-07 09:37:38 [attached_device] AttachedDeviceDriver onInit
2020-02-06 07:48:09 [log] [MyApp] app unload called
2020-02-06 07:45:59 [log] [MyApp] Retrieving known devices list
2020-02-06 07:44:47 [log] [MyApp] Router discovery started
2020-02-06 07:44:43 [log] [MyApp] Retrieving known devices list
2020-02-06 07:44:21 [log] [MyApp] Retrieving known devices list
2020-02-06 07:44:05 [log] [MyApp] Retrieving known devices list
2020-02-06 07:43:10 [log] [MyApp] Retrieving known devices list
2020-02-06 07:41:55 [log] [MyApp] Router discovery started
2020-02-06 07:41:27 [log_analyzer] LogAnalyzerDriver onInit
2020-02-06 07:41:27 [attached_device] AttachedDeviceDriver onInit
2020-02-06 07:41:27 [netgear] NetgearDriver onInit
2020-02-06 07:41:27 [err] [MyApp] error reading logfile: ENOENT: no such file or directory, open '/userdata/netgearLog.json'
2020-02-06 07:41:27 [log] [MyApp] Netgear App is running!
2020-02-06 07:41:27 [log] [MyApp] capturing stderr

**Comment by Hmvink** [comment] 2020-02-07 11:34
I notice that a device is not reporting correctly because when I turn off wifi oon my phone I do not get a notification as I used to. I have several flows that respond somebofy/nobody being home. They do not work anymore.

**Comment by gruijter** [comment] 2020-02-07 11:48
Ah, ok. But can you see in the app logs that the device reports in/out correctly? Maybe the flows don't work anymore.

**Comment by Hmvink** [comment] 2020-02-07 12:10
Good point. I will check later today.

**Comment by mwolfs** [comment] 2020-02-07 13:49
Until now my configuration is running smoothly and stable :-)

**Comment by Hmvink** [comment] 2020-02-08 06:38
This I what I found so far. The app is able to communicate with router. It can get all info as I can see it changing, except for the number of connected devices and the status (connected/disconnected) . That stays the same while I disconnect a device. My flow that runs when a device becomes offline or online therefore never runs.

**Comment by Hmvink** [comment] 2020-02-08 06:39
Oops, wrong post...

**Comment by gruijter** [comment] 2020-02-08 06:45
App version is 3.0.8? If so, can you do another compatibility test from the app settings and post it here?(or the other thread 😜)

**Comment by Hmvink** [comment] 2020-02-08 08:00
My old thread is closed so I cannot post it there anymore. Can you reopen it to keep things organized?

**Closed as completed** 2021-11-26 14:51 UTC
