### ISSUE TITLE
Netgear XR500 Gaming Router

### ISSUE THREAD

**Issue by HenricAsk** [gruijter/com.gruijter.netgear#12] opened 2018-12-09 20:56 UTC
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.2.2
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{Firmware:V2.3.2.32WW,RegionTag:XR500_WW,Region:ww,Model:XR500,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:3.18,ReadyShareSupportedLevel:13,XCloudSupported:1,LoginMethod:2.0,host:192.168.1.201,port:80}
trying to login...
login method: 2
trying to getInfo...
{ModelName:XR500,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V2.3.2.32,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:XR500,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,FirmwareDLmethod:FTP,FirmwareLastUpdate:2018_12.8_1:33:7,FirmwareLastChecked:2018_12.9_15:9:44,DeviceName:XR500,DeviceMode:0}
trying to get supportFeatures...
{SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0}
trying to get Parental Control Status...
{message:Invalid response code from router: 404}
{host:192.168.1.201,port:80,username:admin,password:*****,timeout:10000,sessionId:A7D88AE69687E58D9A00,cookie:[jwt_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOiI4NTAxOCIsImlzcyI6Ind3dy5uZXRnZWFyLmNvbSIsInN1YiI6Im5vZGUtbmV0Z2VhcmpzIn0=.9ea3372d00d63d9dc1ff8fb7780dd07234a5d033a3789e196ccd590367580971],loggedIn:true,configStarted:true,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetEnableStatusResponse xmlns:m=\urn:NETGEAR-ROUTER:service:ParentalControl:1\></m:GetEnableStatusResponse>\r\n<ResponseCode>404</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}

**Comment by gruijter** [comment] 2018-12-09 21:06
Thx for the testlog. If you pair the device in Homey, is it working? Or do you get errors there as well?

**Comment by HenricAsk** [comment] 2018-12-09 21:16
No problems when I pair it to homey. I only noticed the problem because it
didn't register when a device came online or offline.

Den sön 9 dec. 2018 22:06 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-09 21:19
Does it never register a device coming online or going offline?

If you add a action flowcard (e.g. block device by mac) do you get a pulldown list of all devices that are on your network?

And what homey firmware are you on?

**Comment by HenricAsk** [comment] 2018-12-09 21:32
It doesn't register online/offline. I do get a list of devices in the
"block a device" drop-down list. The router says the device is offline but
nothing happens in the flow.

My flow: A device came online - check mac-adress (better logic) - Set
Boolean variable (device is home).



Den sön 9 dec. 2018 22:19 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-09 21:37
But in the app log, do you see messages of devices going online and offline? If you switch the wifi of your phone off for instance, it should report the phone as offline after about 4 minutes. And if you switch wifi on again, it should report it as online after about a minute. Can you post some lines of the app log here?

**Comment by HenricAsk** [comment] 2018-12-09 21:44
Ok I will try more tomorrow and post the logs, need to get my beauty sleep
now 😁 Thanks for fast response and the help this far!

Den sön 9 dec. 2018 22:37 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-09 21:47
😴👻👍

**Comment by HenricAsk** [comment] 2018-12-10 15:17
Hi again

Tried a little more today and it seems like it's working most of the time
atleast.

This is my log for the last hour or so.

2018-12-10 15:41:46 [err] [ManagerDrivers] [netgear] [0]
updateRouterDeviceState error:  socket hang up
2018-12-10 15:41:46 [log] [ManagerDrivers] [netgear] [0] undefined
2018-12-10 15:41:46 [log] [ManagerDrivers] [netgear] [0] last repsonse from
router:
2018-12-10 15:35:41 [log] [ManagerDrivers] [netgear] [0] Offline:
28:b2:bd:33:e5:82 DESKTOP-CJJCTNU
2018-12-10 15:33:41 [log] [ManagerDrivers] [netgear] [0] Online:
dc:66:72:ad:9e:cf Min platta 192.168.1.14
2018-12-10 15:32:41 [log] [ManagerDrivers] [netgear] [0] Offline:
dc:66:72:ad:9e:cf Min platta
2018-12-10 15:30:41 [log] [ManagerDrivers] [netgear] [0] Online:
4c:ed:fb:94:8b:ad Min dator 192.168.1.180
2018-12-10 15:29:41 [log] [ManagerDrivers] [netgear] [0] Offline:
b8:27:eb:6d:51:5c RASPBERRYPI

Den sön 9 dec. 2018 kl 22:47 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-10 21:10
Actually, this response looks pretty normal. So your flows should work. Maybe you should replace the condition card with the regular Homey logic, in stead of better logic. That is what I'm using myself, and it works fine.

I do see however that I need to adapt the test, so that it doesn't stop on an error. In your case, your router doesn't support parental control. This is no problem at all for Homey, but the test does not finish, so it might seem to you something is wrong. I will change that in a next version. So thx for the feedback!

**Comment by HenricAsk** [comment] 2018-12-10 21:51
I think I got it to work now. I replaced the trigger to a timer instead of
device went online/offline. The timer then check every 10 sec if the device
is connected to the router or not.
It seems as sometimes the trigger (device went online/offline) misses when
a device goes online or offline and then it won't fire the events.
Why this happens I don't know.
One thing you could change if it's possible is, I can't add a mac-adress to
the flow if the device is offline (the mac-adress is not in the drop-down
list).

Thank you very much for your support, keep up the good work.



Den mån 10 dec. 2018 22:10 skrev gruijter <notifications@github.com>:

**Comment by HenricAsk** [comment] 2018-12-11 08:46
Hi again :)

Hope you're not getting tired of me :)
Found this "bug", the device isn't connected to the router but it still
goes to ...then and not to ...else.

[image: bild.png]

Den mån 10 dec. 2018 kl 22:51 skrev Henric Mathias Ask <
henricask2000@gmail.com>:

**Comment by gruijter** [comment] 2018-12-11 13:51
Absolutely no problem. In fact I'm happy with your feedback because it helps me improve the app.

Did you intend to attach an image? Because I do not see it. Your desription is not really clear to me? Could you repost the screenshot?

**Comment by HenricAsk** [comment] 2018-12-11 14:16
Yes there was a screenshot. I'll try it this way instead.

Den tis 11 dec. 2018 14:51 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-11 17:26
Still no screenshot😮

**Comment by HenricAsk** [comment] 2018-12-11 18:37
Then I will try a Zip-file :)

Den tis 11 dec. 2018 kl 18:26 skrev gruijter <notifications@github.com>:

**Comment by HenricAsk** [comment] 2018-12-11 18:43
![bild](https://user-images.githubusercontent.com/45741708/49822278-f56af680-fd7c-11e8-9f01-9cdff83c18b7.png)

**Comment by gruijter** [comment] 2018-12-11 19:19
Well, this looks like a Homey bug actually, and not a bug in the netgear app.

**Comment by HenricAsk** [comment] 2018-12-11 19:50
Seems like you are right, restarted my Homey and everything was fine again. However I managed to reproduce the problem and it happens when I change "Offline after (seconds)" settings in your app. As soon as I changed that value Homey "crash" like the picture shows. So if the problems lies with the app or Homey itself I don't know :)

**Comment by gruijter** [comment] 2018-12-13 08:27
Well, it takes a minute or two after restarting the app to get the status of a device. So if you try this flow too soon, you will get an error. After the startup time it works fine.

**Comment by HenricAsk** [comment] 2018-12-14 10:32
The problem came back, restarted Homey and waited a couple of hours but
still the same problem. Restarted your program and waited but nu luck their
either.
I had to remove your app and reinstall it again. Problem fixed. Or so I
thought atleast but today when I restarted my Homey again (and waited an
hour) the problem is back.
It´s only the flows where I use the Netgear app the problems appears.

Den tors 13 dec. 2018 kl 09:27 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-16 21:08
What Homey version are you on?

**Comment by HenricAsk** [comment] 2018-12-16 21:09
1.5.13

Den sön 16 dec. 2018 kl 22:08 skrev gruijter <notifications@github.com>:

**Comment by HenricAsk** [comment] 2018-12-16 21:16
I noticed one thing thats a little odd. When I reboot the Homey does the "known" devices list get cleared?
Because when I rebooted and one of the devices was not home that flow got screwed up like the picture I sent u. Is there any way for that list to be saved even after a reboot?

**Comment by gruijter** [comment] 2018-12-16 21:19
The list is stored and survives a reboot. You van erase the list via device setting.

**Comment by HenricAsk** [comment] 2018-12-16 21:25
Ok, but when I saw that problem after a reboot i tried to reenter that mac-adress for that device and it was not in the dropdown list. So I had to wait until that device came home then I could reenter it... And when the device had been added to the dropdown list everything worked again. Until the next reboot, same problem again. The devices that are home works but not the ones that are not home.

**Comment by gruijter** [comment] 2018-12-16 21:32
Ok thx for the info. Ill see if I can reproduce and find something in the code that could cause this effect.

**Comment by gruijter** [comment] 2018-12-20 08:28
I suspect that one of your devices has 'illegal' characters in its name. Could you try deleting the known devices list via device setting? Or even better: fully delete the app and reinstall. I wonder if that makes a change. Also check the debug log in the app settings screen. See if you find devices that have a weird name. After deleting the known devices you should see all connected devices coming up as 'new device'

**Comment by HenricAsk** [comment] 2018-12-20 10:16
I will try!

Den tors 20 dec. 2018 09:28 skrev gruijter <notifications@github.com>:

**Comment by HenricAsk** [comment] 2018-12-20 10:58
Seems like it's working now :) Even if the device isn't in the list the flow goes the right "way". Could it be that if I change a device name in my router that it screws up the list in Homey? (two names with same mac?)

**Comment by gruijter** [comment] 2018-12-22 11:40
shouldn't matter if you change the name in Homey. Did you try if that causes problems for you?

**Comment by HenricAsk** [comment] 2018-12-22 11:43
I mean to change the name in router not in homey. I haven't tried if that's
the case but I can do it later today.

Den lör 22 dec. 2018 12:40 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-22 11:44
Ah, ok. Actually I have changed devices names in the router myself, and for me this is not causing problems.

**Comment by HenricAsk** [comment] 2018-12-22 11:50
Oh well then it's not that either. But it's working now at least so
clearing the list seems like the solution to this problem. The only
question is what characters is illegal? I live in Sweden so we have for
example å ä ö in our alfabet but I'm using those characters now and it's
working.

Den lör 22 dec. 2018 12:44 skrev gruijter <notifications@github.com>:

**Comment by gruijter** [comment] 2018-12-22 13:15
I'm not sure on what characters the code could choke. Maybe you already renamed the device that had illegal characters in its name. Anyhow, I'm closing the issue. Please reopen if you have the problem again, or if you find out what is causing the issue.
Thx for your feedback!

**Closed as completed by gruijter** 2018-12-22 13:15 UTC

**Comment by HenricAsk** [comment] 2018-12-22 13:19
Thanks for your help and keep up the great work!

Den 22 dec. 2018 14:15 skrev "gruijter" <notifications@github.com>:

I'm not sure on what characters the code could choke. Maybe you already
renamed the device that had illegal characters in its name. Anyhow, I'm
closing the issue. Please reopen if you have the problem again, or if you
find out what is causing the issue.
Thx for your feedback!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gruijter/com.gruijter.netgear/issues/12#issuecomment-449569397>,
or mute the thread

**Comment by gruijter** [comment] 2018-12-24 19:21
After extensive digging I found an issue indeed with persistent strorage in Homey. I'm still not sure what exactly is causing it. It seems to be weird device names. I made a workaround now that should keep the error from happening again.

I will soon upload a new version to the appstore.

**Comment by HenricAsk** [comment] 2018-12-24 19:42
Thanks for doing everything you can to fix the problem. In fact I had the
problem again today but clearing the known devices list fix the problem for
the time being. I have now tried to rename all the connected devices on the
router. No "wierd" names, no spaces and no device with the same name (have
2 Chromecasts and they had the same name). Will see if the problem
disappear after this.

Den mån 24 dec. 2018 20:21 skrev gruijter <notifications@github.com>:
